apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv2
spec:
  capacity:
    storage: 1Gi  # Adjust the storage size as needed
  accessModes:
    - ReadWriteOnce  # Change if needed
  hostPath:  # Using hostPath for local testing (change for production)
    path: D:\KubeSync\Yamls  # Change to a valid path on the node
