apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service2
spec:
  type: NodePort
  selector:
    app: my-app2  # Ensure this matches the Pod's labels
  ports:
    - port: 8080  # Port the service will expose
      targetPort: 8080  # Port on the Pod where the application is listening
      nodePort: 30002  # Specify a custom NodePort or let Kubernetes assign one
